services:
  - type: web
    name: imperion-ai
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1